build musl arm and amd64 toolchains as part of build

diff --git a/script/release-build-musl b/script/release-build-musl
--- a/script/release-build-musl
+++ b/script/release-build-musl
@@ -44,25 +44,53 @@ echo "Cleaning bin folder…"
 date "+%H:%M:%S"
 ./script/clean
 
+if ! type "x86_64-linux-musl-cc" > /dev/null; then
+    echo "x86_64-linux-musl-cc not found installing…"
+    git clone https://github.com/richfelker/musl-cross-make.git ./musl-build
+    cd ./musl-build
+    TARGET=x86_64-linux-musl
+    make
+    make install
+    TARGET=aarch64-linux-musl
+    make
+    make install
+    cd ..
+
+    MUSL_BIN="$(PWD)/musl-build/output/bin/"
+    PATH=$PATH:$MUSL_BIN;
+fi
+
 
 echo "Building embedded binary for linux-amd64…"
 date "+%H:%M:%S"
-touch ./cmd/root/ddcbinary/output/ddc.zip
-GCO_ENABLED=1 CC=musl-gcc GOOS=linux GOARCH=amd64 go build -ldflags "$LDFLAGS -linkmode external -extldflags \"-static\"" -o ./bin/ddc ./cmd/local/main
-cp ./default-ddc.yaml ./bin/ddc.yaml
+
+CC=x86_64-linux-musl-cc CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags "$LDFLAGS" -o ./bin/ddc ./cmd/local/main
 zip ./bin/ddc.zip ./bin/ddc
+mv ./bin/ddc.zip ./cmd/root/ddcbinary/output/ddc-amd64.zip
 rm ./bin/ddc
-mv ./bin/ddc.zip ./cmd/root/ddcbinary/output/ddc.zip
+
+echo "Building embedded binary for linux-arm64…"
+date "+%H:%M:%S"
+
+CC=aarch64-linux-musl-cc CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -ldflags "$LDFLAGS" -o ./bin/ddc ./cmd/local/main
+zip ./bin/ddc.zip ./bin/ddc
+mv ./bin/ddc.zip ./cmd/root/ddcbinary/output/ddc-arm64.zip
+rm ./bin/ddc
+
+
 echo "Building linux-amd64…"
 date "+%H:%M:%S"
-GCO_ENABLED=1 CC=musl-gcc GOOS=linux GOARCH=amd64 go build -ldflags "$LDFLAGS -linkmode external -extldflags \"-static\"" -o ./bin/ddc
+GCO_ENABLED=1 CC=x86_64-linux-musl-cc GOOS=linux GOARCH=amd64 go build -ldflags "$LDFLAGS -linkmode external -extldflags \"-static\"" -o ./bin/ddc
 zip ./bin/ddc-linux-amd64.zip ./bin/ddc ./bin/ddc.yaml ./README.md ./FAQ.md
 echo "Building linux-arm64…"
 date "+%H:%M:%S"
-GOOS=linux GOARCH=arm64 go build -ldflags "$LDFLAGS" -o ./bin/ddc
+
+
+GCO_ENABLED=1 CC=aarch64-linux-musl-cc GOOS=linux GOARCH=arm64 go build -ldflags "$LDFLAGS -linkmode external -extldflags \"-static\"" -o ./bin/ddc
 zip ./bin/ddc-linux-arm64.zip ./bin/ddc ./bin/ddc.yaml ./README.md ./FAQ.md
 echo "Building darwin-os-x-amd64…"
 date "+%H:%M:%S"
+
 GOOS=darwin GOARCH=amd64 go build -ldflags "$LDFLAGS" -o ./bin/ddc
 zip ./bin/ddc-mac-intel.zip ./bin/ddc ./bin/ddc.yaml ./README.md ./FAQ.md
 echo "Building darwin-os-x-arm64…"
